version: "3.7"

services:

  reverseproxy:
    build:
      context: ./Nginx
      dockerfile: Nginx.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/https:ro
    restart: always

  app:
    depends_on:
      - reverseproxy
    build:
      context: ./
      dockerfile: App.Dockerfile
    expose:
      - "5003"
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/https/live/v2160200.hosted-by-vdsina.ru/privkey.pem
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/live/v2160200.hosted-by-vdsina.ru/fullchain.pem
    volumes:
      - /etc/letsencrypt:/https:ro
    restart: always